language: node_js
node_js:
  - node

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH

install:
- yarn global add grunt-cli
- yarn install

script:
- grunt check
- yarn test -- --coverage

after_success:
- yarn global add codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info

notifications:
  slack:
    secure: W3StABr+AdcdQawTObK4nbsnn5nLrTTtZfVpD/GEN6gvSOQcykbGEC5+ceYg0jn5b4StDyCiTo5blEsrpVICFpYKc44+ogah+qaGRUfVRS/rpOvn4AueXTWn4JxhZzuxqKMiTmyW+MQG0uYM7sk7Q5S+15jj6ilkj4QATaBVNbY=
